(define (largestsum x y z)
  (cond (and (> x y) (> x z) (> y z) (+(* x x) (* y y)))
        (and (> y z) (> y x) (> z x) (+(* y y) (* z z)))
        (and (> x y) (> x z) (> z y) (+(* x x) (* z z)))
  ))
